<?php

/**
 * @file
 * Provides additional CiviCRM related properties for module ThemeKey.
 */

/**
 * Implements hook_themekey_properties().
 *
 * Provides additional properties for module ThemeKey:
 * - civicrm:contribution_page:id
 * - civicrm:contribution_page:type
 * - civicrm:event:id
 * - civicrm:event:type
 */
function themekey_civicrm_themekey_properties() {
  // Attributes for properties.
  $attributes = array();

  $attributes['civicrm:contribution_page:id'] = array(
    'description' => t("CiviCRM: Contribution Page ID - The ID of the CiviCRM Contribution Page currently being viewed."),
    'page cache' => THEMEKEY_PAGECACHE_SUPPORTED,
  );
  $attributes['civicrm:contribution_page:type'] = array(
    'description' => t("CiviCRM: Contribution Type - The type of Contribution Page currently being viewed."),
    'page cache' => THEMEKEY_PAGECACHE_SUPPORTED,
  );
  $attributes['civicrm:event:id'] = array(
    'description' => t("CiviCRM: Event ID - The ID of the CiviCRM Event currently being viewed."),
    'page cache' => THEMEKEY_PAGECACHE_SUPPORTED,
  );
  $attributes['civicrm:event:type'] = array(
    'description' => t("CiviCRM: Event Type - The type of the CiviCRM Event currently being viewed."),
    'page cache' => THEMEKEY_PAGECACHE_SUPPORTED,
  );

  // These properties require some extra logic to be set.
  // So we delegate to mapping functions which will only be called
  // right when property occurs in a Theme Switching Rule.
  $maps = array();
  $maps[] = array(
    'src'       => 'system:dummy',
    'dst'       => 'civicrm:contribution_page:id',
    'callback'  => 'themekey_civicrm_dummy2contribution_page_id',
  );
  $maps[] = array(
    'src'       => 'system:dummy',
    'dst'       => 'civicrm:contribution_page:type',
    'callback'  => 'themekey_civicrm_dummy2contribution_page_type',
  );
  $maps[] = array(
    'src'       => 'system:dummy',
    'dst'       => 'civicrm:event:id',
    'callback'  => 'themekey_civicrm_dummy2event_id',
  );
  $maps[] = array(
    'src'       => 'system:dummy',
    'dst'       => 'civicrm:event:type',
    'callback'  => 'themekey_civicrm_dummy2event_type',
  );

  return array('attributes' => $attributes, 'maps' => $maps);
}

/**
 * Helper function to load details of a CiviCRM entity.
 */
function _themekey_civicrm_entity_load($entity_type, $id) {
  if (!civicrm_initialize()) {
    return NULL;
  }
  try {
    $result = civicrm_api3($entity_type, 'get', [
      'id' => $id,
      'sequential' => 1,
    ]);

    if (!empty($result['values'][0])) {
      return $result['values'][0];
    }
  }
  catch (Exception $e) {
    watchdog('themekey_civicrm', 'API exception: %message', ['%message' => $e->getMessage()], WATCHDOG_ERROR);
  }
}

/**
 * Map ThemeKey property's value (destination) from ThemeKey property (source).
 *
 * @return string
 *   id of contribution page
 */
function themekey_civicrm_dummy2contribution_page_id() {
  if (!civicrm_initialize()) {
    return NULL;
  }
  $qfKey = NULL;
  $session_data = NULL;
  if (array_key_exists('qfKey', $_REQUEST)) {
    $qfKey = $_REQUEST['qfKey'];
    if (array_key_exists('CRM_Contribute_Controller_Contribution_' . $qfKey, $_SESSION['CiviCRM'])) {
      $session_data = $_SESSION['CiviCRM']['CRM_Contribute_Controller_Contribution_' . $qfKey];
    }
  }
  $acceptable_paths = _themekey_civicrm_get_contribution_paths();
  if (array_key_exists('q', $_GET) && in_array($_GET['q'], $acceptable_paths)) {
    if (!empty($_GET['id'])) {
      $contribution_page_id = $_GET['id'];
    }
    elseif (!is_null($session_data)) {
      if (!empty($session_data['id'])) {
        $contribution_page_id = $session_data['id'];
      }
    }
    else {
      require_once 'CRM/Core/Session.php';
      $session = CRM_Core_Session::singleton();
      $contribution_page_id = $session->get('pastContributionID');
    }
  }
  return !empty($contribution_page_id) ? $contribution_page_id : NULL;
}

/**
 * Map ThemeKey property's value (destination) from ThemeKey property (source).
 *
 * @return string|null
 *   id of the event
 */
function themekey_civicrm_dummy2event_id() {
  $event_id = NULL;
  if (!civicrm_initialize()) {
    return NULL;
  }
  $qfKey = NULL;
  $session_data = NULL;
  if (array_key_exists('qfKey', $_REQUEST)) {
    $qfKey = $_REQUEST['qfKey'];
    // Should this work? It doesn't on validation page.
    if (array_key_exists('CRM_Event_Controller_Registration_' . $qfKey, $_SESSION['CiviCRM'])) {
      $session_data = $_SESSION['CiviCRM']['CRM_Event_Controller_Registration_' . $qfKey];
    }
  }
  $acceptable_paths = _themekey_civicrm_get_event_paths();
  if (array_key_exists('q', $_GET) && in_array($_GET['q'], $acceptable_paths)) {
    if (!empty($_GET['id'])) {
      $event_id = $_GET['id'];
    }
    elseif (!is_null($session_data)) {
      if (!empty($session_data['id'])) {
        $event_id = $session_data['id'];
      }
    }
    else {
      require_once 'CRM/Core/Session.php';
      $session = CRM_Core_Session::singleton();
      $event_id = $session->get('pastEventID');
    }
    // Hail Mary fallback: look for _entryURL.
    if (is_null($event_id) && isset($_SESSION['CiviCRM']['entryURL'])) {
      // http://yfnz.fudev.co.nz/civicrm/event/register?reset=1&amp;action=preview&amp;id=79
      $url = $_SESSION['CiviCRM']['entryURL'];
      $url = str_replace('&amp;', '&', $url);
      $p_url = parse_url($url);
      $p_query = drupal_parse_url($p_url['path'] . '?' . urldecode($p_url['query']));
      $event_id = $p_query['query']['id'];
    }
  }
  return !empty($event_id) ? $event_id : NULL;
}

/**
 * Map ThemeKey property's value (destination) from ThemeKey property (source).
 *
 * @return string|null
 *   id of the event page
 */
function themekey_civicrm_dummy2contribution_page_type() {
  if ($contribution_page_id = themekey_civicrm_dummy2contribution_page_id(NULL)) {
    if ($page = _themekey_civicrm_entity_load('ContributionPage', $contribution_page_id)) {
      $contribution_page_type_id = $page['contribution_type_id'];
    }
    return !empty($contribution_page_type_id) ? $contribution_page_type_id : NULL;
  }
}

/**
 * Map ThemeKey property's value (destination) from ThemeKey property (source).
 *
 * @return string|null
 *   Id of the contribution page being viewed.
 */
function themekey_civicrm_dummy2event_type() {
  if ($event_id = themekey_civicrm_dummy2event_id()) {
    if ($event = _themekey_civicrm_entity_load('Event', $event_id)) {
      $event_type_id = $event['event_type_id'];
    }
    return !empty($event_type_id) ? $event_type_id : NULL;
  }
}

/**
 * Helper function to return a list of contribution-related civicrm paths.
 */
function _themekey_civicrm_get_contribution_paths() {
  return array(
    // Standard URL.
    'civicrm/contribute/transact',
    // Users visiting a personal campaign page.
    'civicrm/pcp/info',
    // Users creating theirown personal campaign page (pageId).
    'civicrm/contribute/campaign',
    // These are from ./CRM/Contribute/xml/Menu/Contribute.xml
    // (not sure how exactly they are accessed).
    'civicrm/contribute/additionalinfo',
    'civicrm/contribute/unsubscribe',
    'civicrm/contribute/onbehalf',
    'civicrm/contribute/updatebilling',
    'civicrm/contribute/updaterecur',
    'civicrm/contribute/subscriptionstatus',
  );
}

/**
 * Helper function to return a list of event-related civicrm paths.
 */
function _themekey_civicrm_get_event_paths() {
  return array(
    'civicrm/event/info',
    'civicrm/event/register',
  );
}
